### ISSUE TITLE
Multi-followup observations for GRB in a single night

### ISSUE THREAD

**Issue by ewittmyl** [GOTO-OBS/gtecs-alert#18]
I think for most of the GRB afterglow, they would have a significant fading rate especially within the first night of the trigger. I have discussed with Duncan that we both agree to modify our scheduler for following up a single GRB at least twice within the first night of the trigger. For the cases, if we miss the first day of the trigger (>6hrs post burst), maybe we do not need to do so.  And I believe the second observation on the first night should be  ~4 hours after the first one.

**Comment by martinjohndyer** [comment]
So I've been thinking about this, and I'm a little worried our current `TimeBlock` system isn't quite flexible enough for this. It's complicated enough as it is, but the idea is to make fixed blocks with valid times and wait times. Everything's scheduled to specific time stamps, so it's not easy to say "schedule this pointing for 4 hours after the previous one was completed".

Not that that's not doable, it might be an interesting project to work on when I'm visiting in May.

**Comment by martinjohndyer** [comment]
This was added a while ago, I think in https://github.com/GOTO-OBS/gtecs-alert/pull/31?
