### ISSUE TITLE
Lessons from new BNS events

### ISSUE THREAD

**Issue by martinjohndyer** [GOTO-OBS/gtecs-alert#26]
So we've had two actual BNS/NSBH events that we tried to follow up with GOTO. For S190425z and S190426c I ended up doing a fair amount of database insertion myself, from the EMMA workshop in Baltimore. There were a few reasons for that:
* The sentinel failed a couple of times thanks to the way skymaps are stored in the XML VOEvents. See #24 and #25, should be fixed going forward.
* There was a later LVC skymap that also failed due to a problem on LIGO's end (for ivo://gwnet/LVC#S190426c-4-Update). Nothing to do with me, and they did release an update ~45 minutes later. However due to the way the code is ordered the previous tiles were deleted before creating the new ones, so had we been observing we would have had a very annoying gap.
* The first event, 25z, had an incredibly large and wide skymap. The sentinel has a default cutoff for tiles of 1% for GW events (5% for GRBs) and no tiles were above this. To do it manually I had to go down to 0.1%. The 26c skymap was also pretty large, and I lowered the limit to 0.5%.
* The priority was determined to be coverage over repeat visits. The sentinel would only insert a maximum of 50 tiles for GW events, and when we can observe ~130 in a good night we'd prefer to do as many tiles as possible (with a reasonable probability).
* The other thing I considered was visibility. The sentinel is deliberately ambivalent to this, but manually I could use Astroplan to limit the tiles I put in. I don't want GOTO-alert to start doing that, although it might be handy for the sentinel alerts. But that was how I selected the probability limits, which makes it a little harder to do automatically. I suppose the difference there is between altitude and solar limits, the latter will apply wherever you are on Earth so might be reasonable for this module to consider.

Obviously the idea is I shouldn't be needed - the sentinel using GOTO-alert (and GOTO-tile) should insert the pointings it needs.

So, the question is how do we remove the human element? Well #22 is a start, but needs more...

**Comment by martinjohndyer** [comment]
So as a start, we can try increasing the limits to roughly what I set during that busy two days in Baltimore: prob > 0.001 and, in case it's needed, N < 200. Visibility isn't really an issue, aside from filling up the database the scheduler will do that work.

That works fairly well, although for smaller maps like 190426c and 170817 you'll add a lot more tiles than perhaps is reasonable.

So instead, how about limiting based on something else: like the highest single probability in a tile? The size of the confidence regions?

|          | Limit used | Tiles added | All tiles* | Highest prob | 90% frac | 50% frac |
|----------|------------|-------------|------------|--------------|----------|----------|
| S190425z | 0.001      |          88 |        303 |       0.0135 |   0.1809 |  0.03339 |
| S190426c | 0.005      |          49 |         54 |       0.1217 |   0.0274 |  0.00519 |

It's a tough one, and honestly something that needs to be played with in some simulations. One slightly interesting thing that illustrates the problem is that with a limit of 0.005 you get 59 tiles for 190425z and 54 for 190426c, but for 190425z those tiles cover ~35% of the probability where as for 190426c they cover ~80%. Anyway I guess the idea is we need something that's in roughly 1/5 ratio set for the limits this time. The best I can see there is the 50% fraction, which comes out to 1/6.4. If your limit is L=x/(50% frac) where x found by these two events is 0.0003 you get 333 tiles for 190425z and 51 for S190426c, or 41 and 100 when visibility is applied. That's good enough for now, so I'll code that in.

**Comment by martinjohndyer** [comment]
This needs some more tweaking, it only added 4 tiles for 190510's revised map covering ~60%. There should be a better method, aiming to cover a certain percentage perhaps.

Also I'm not sure about the delay between pointings, we had some time in the morning where we looked at survey tiles and it might have been more useful to revisit the tiles we'd already done.

**Comment by dsteeghs** [comment]
Indeed, it might be simpler to stick to (immediate) repeats after all, as a sensible gap depends on so many things and is not so easy to define. Certainly more often it will make sense to repeat than to wait.

**Comment by martinjohndyer** [comment]
Here's another option: using the new contour functions from GOTO-tile. The `get_contour` and `within_contour` methods on `SkyGrids` can take arrays of `SkyCoords`, for example the tile centres. So it's actually really easy to mask tiles based on if they are within the contour regions:

```python
import gototile
skymap = gototile.skymap.SkyMap.from_fits('https://gracedb.ligo.org/api/superevents/S190510g/files/bayestar.fits.gz')
grid = gototile.grid.SkyGrid((3.7,4.9), (0.1,0.1))

mask_50 = skymap.within_contour(grid.coords, 0.9)
tiles_within_50 = np.array(grid.tilenames)[mask]

mask_90 = skymap.within_contour(grid.coords, 0.5)
tiles_within_90 = np.array(grid.tilenames)[mask]
```
Note you don't even need to apply the skymap to the grid.
Now this isn't a perfect use of the grid since it's only considering the centre points. MAybe it would be better to get the contour pixels and then find all the tiles that contain a certain fraction of them? But for now this will work fine.

Here's the final skymap, and the resulting tiles, for the S190510g event:

![skymap2_contours](https://user-images.githubusercontent.com/15014527/57903745-584e4580-7867-11e9-8b4f-b133fd8c88d2.png)
![skymap2_tiles](https://user-images.githubusercontent.com/15014527/57903755-68662500-7867-11e9-8567-6c2cb965bbf4.png)


Here are the tile numbers for the three most recent events, if you select based on the 50% or 90% contours:

|          | 50% tiles | Total covered | 90% tiles | Total covered |
|----------|-----------|---------------|-----------|---------------|
| S190425z |        99 |           50% |       529 |           89% |
| S190426c |        13 |           45% |        82 |           90% |
| S190510g |         3 |           56% |        82 |           89% |

So if we're going by what we entered manually for the first two events (303/54) we actually want somewhere between the two - 80% for example gives 326/45. But the 90% region is an established thing, so it's probably easiest to go with that.

**Comment by martinjohndyer** [comment]
The above still isn't perfect, thanks to our fixed grid. If we only select based on the tile centres we can miss chunks of even the 50% area, as the plot below shows (see T2735 towards the top centre):

![test_centres2](https://user-images.githubusercontent.com/15014527/57989995-0a6d5380-7a9a-11e9-9bf0-4a674e297e1f.png)


A better solution would instead to find the area of each tile that is within the 90% region, and then select based on that.

There are a few ways to do that. For example, it's simple enough to get the mean contour value within the tile area:

```
tile_cons = [np.mean(skymap.contours[tile_pix]) < 0.9 for tile_pix in grid.pixels]
```

Masking on a mean contour value of < 0.9 produces a more reasonable result, T2735 for example gets in as it's mean value is 70%. 98 tiles for this skymap, compared to the 73 for the previous, centre-based method.

Another simple option if you wanted to be sure to cover an entire contour would be to filter based on the maximum pixel value:

```
tile_cons = [np.min(skymap.contours[tile_pix]) < 0.5 for tile_pix in grid.pixels]
```

This would force full coverage of every tile with a single pixel within the 50% region, which in this case is 99 and therefore basically the same as above. For the whole 90% region you'll obviously cover a lot more.

Here's yet another table of our three previous events, with these new methods:


|          | mean < 90% | Covered | min < 50% | Covered | min < 90% | Covered |
|----------|------------|---------|-----------|---------|-----------|---------|
| S190425z |        546 |   90.4% |       196 |   65.2% |       723 |   94.4% |
| S190426c |         82 |   89.9% |        39 |   72.3% |       135 |   95.0% |
| S190510g |         81 |   89.7% |         6 |   66.4% |       137 |   92.0% |

And to visualise it, here's a plot of the above applied to S190510g. It's notable for a very small 50% region, only 6 tiles here (in red). The 137 tiles to cover the entire 90% region are in red+yellow+green. And finally the compromise between the two, the tiles with a mean of < 90% are in red+yellow.

![test_meanmin](https://user-images.githubusercontent.com/15014527/57990405-46a2b300-7a9e-11e9-9aa2-aec72c5234de.png)

As always, this could probably use more testing and simulations, and could be revisited as our fov increases. But taking the mean < 90% seems to be a fair compromise - in the above case you'd add an extra 56 tiles to your 81 only for a gain of 2.3%. So for now I'll code that in to #22.
