### ISSUE TITLE
Decide if event is worth following up

### ISSUE THREAD

**Issue by Ry-C123** [GOTO-OBS/gtecs-alert#32]
As we can now predict the probability region viable, we should decide if an event is worth following up or if there's more to gain just staying in survey mode.

The logic could use features like:
- Probable region covered  (e.g. < 10% covered should be ignored)
- Area of localisation (larger localisations should have lower probability constraints)
- Distance of source (We will never see something 1000000Mpc away)
etc. 

The criteria should be discussed further, but I thought the basic idea should be posted :) .

**Comment by martinjohndyer** [comment]
Good idea @ryanc123, that's absolutely something we should consider. I think it would be fairly easy to work into the new alert logic added in #31.

There is also a fourth parameter for GW events, the False-Alarm Rate we get from LIGO. We could definitely chose to not follow up targets with too low a FAR. There are also things like the number of detectors the signal was seen in, or the p(Terrestrial), but I believe they're included in the FAR.

**Comment by ryanc123** [comment]
I wasn’t sure about the FAR/ p(terrestrial). In that, if we decide not to follow up an event and it gets updated to being a true event we lose time in not following it up.

But I guess that’s the risk with any decision 😋 I’ll post a poll or something to slack and see democracy come up with a solution nobody likes!

**Comment by martinjohndyer** [comment]
As of #73 we do actually ignore some alerts now.
